compare/urls.py
from django.conf.urls import url
from compare import views


app_name = 'compare'

urlpatterns = [
    url(r'^$', views.compare, name='compare'),
]

stockviz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from compare import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^compare/', include('compare.urls'))
]

compare/models.py
from django.db import models

class Ticker(models.Model):
    ticker = models.CharField(max_length=10)

    def __str__(self):
        name = self.ticker
        return name

compare/forms.py
from django import forms
from compare.models import Ticker

class NewTicker(forms.ModelForm):
    class Meta():
        model = Ticker
        fields =  '__all__'

compare/views.py
from django.shortcuts import render
from compare.forms import NewTicker
import os
import datetime as dt
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
import pandas_datareader.data as web

def index(request):
    """
    form = NewTicker()

    if request.method == 'POST':
        form = NewTicker(request.POST)

        if form.is_valid():
            form.save(commit=True)
        else:
            print("ERROR!")
    """
    return render(request,'compare/index.html')

def compare(request):
    def graphing():
        style.use('ggplot')

        start = dt.datetime(2012,1,1)
        end = dt.datetime(2016,12,31)

        df = pd.read_csv("compare/sp500_joined_closes.csv", parse_dates=True, index_col=0)

        ax1 = plt.subplot2grid((6,1), (0,0), rowspan=5, colspan=1)

        ax1.plot(df.index, df['F'])
        ax1.plot(df.index, df['INTC'])
        plt.legend()

        plt.plot()
        #os.chdir('..')
        plt.savefig('static/images/foo.png', transparent=True)

    #def fundamentals(request):


    graphing()

    return render(request, "compare/compare.html")

templates/compare/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Stockviz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static "images/shopifylogo.png" %}" width="120" height="36" class="d-inline-block align-top" alt="">
        </a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'compare:compare' %}">Compare</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </div>

    </nav>

    <div class="jumbotron">
      <div class="container">

      {% block body_block %}
      {# Anything outside of this will be inherited if you use extend.#}
      {% endblock %}

      </div>
    </div>
    <script src="{% static "javascript/myscript.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

templates/compare/compare.html
<!DOCTYPE html>
{% extends "compare/base.html" %}
{% load staticfiles %}
  {% block body_block %}
  <link rel="stylesheet" href="{% static "css/compare.css" %}">
    <h1 align="center">AAPL vs MSFT</h1>
    <p align="center">Note: this is just an example. Stockviz is not working yet :(</p>
    <p align="center">Lots of fundamental analysis and difference calculations will follow downstairs</p>
    <img id="graph" src="{% static "images/foo.png" %}" alt="Uh Oh, didn't show!">

    <div id="alltickers" class="container">
      <div class="row">
        <div id="leftcol" class="col">
          <h2>Apple Inc.</h2>
        </div>
        <div id="rightcol" class="col">
          <h2>Microsoft</h2>
        </div>
      </div>
    </div>
  {% endblock %}

templates/compare/index.html
<!DOCTYPE html>
{% extends "compare/base.html" %}
{% load staticfiles %}
  {% block body_block %}
    <link rel="stylesheet" href="{% static "css/indexstyle.css" %}">
    <img class="mainlogo" src="{% static "images/shopifylogo.png" %}" width="300" height="90" alt="oops"><br>
    <p class="lead" align="center">Stockviz helps to compare up to 3 stocks for investing/trading purposes by nicely visualizing differences in financials and other data.</p>
    <p id="intro" class="lead" align="center">Either type in quotes and add them to the comparision or search for
      companies by their industry. S&P500 only at the moment.</p>
    <hr>

    <div id="options" class="container">
      <div class="row">
        <div id="leftcol" class="col">
          <form id="form" onsubmit="return false;">
            <input type="text" id="userInput"><br><br>
            <input type="submit" class="btn btn-dark my-2 my-sm-0" value="Add symbol" onclick="save_input()">
          </form><br>
          <p>Chosen ticker: <b id='current'></b></p>
          <p>All tickers (max 3):</p>
          <div id="tickers" class="divTickers">
            <ul class="list-group" id="tickerList">
              <!--
              <li id="favourite" class="list-group-item">Something</li>
              <li class="list-group-item">Something</li>
              <li class="list-group-item">Something</li>
            -->
            </ul>
          </div>
          <!--
          <form method="POST">

            <input type="submit" class="btn btn-dark my-2 my-sm-0" value="Add symbol">
          </form>
        -->
        </div>
        <div id="rightcol" class="col">
          <p class="lead"><strong>Select an industry</strong></p>
          <table>
            <div class="industries">
              <button type="button" class="btn btn-outline-dark">Energy</button>
              <button type="button" class="btn btn-outline-dark">Materials</button>
              <button type="button" class="btn btn-outline-dark">Industrials</button>
              <button type="button" class="btn btn-outline-dark">Consumer Discretionary</button>
              <button type="button" class="btn btn-outline-dark">Consumer Staples</button>
              <button type="button" class="btn btn-outline-dark">Health Care</button>
              <button type="button" class="btn btn-outline-dark">Financials</button>
              <button type="button" class="btn btn-outline-dark">Information Technology</button>
              <button type="button" class="btn btn-outline-dark">Telecommunication Services</button>
              <button type="button" class="btn btn-outline-dark">Utilities</button>
              <button type="button" class="btn btn-outline-dark">Real Estate</button>
            </div>
          </table>
        </div>
      </div>
    </div>

    <br>

  {% endblock %}